version: 2
sources:
  - name: raw
    database: bluemar_dev_db
    schema: raw
    tables:
      - name: processed_gastos_operativos
      - name: processed_ingresos
      - name: processed_pago_planillas
      - name: processed_inventario_de_activos