USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE BLUEMAR_DEV_ELT_WH WITH WAREHOUSE_SIZE = 'X-SMALL';
CREATE DATABASE BLUEMAR_DEV_DB;
CREATE ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE;

SHOW GRANTS ON WAREHOUSE BLUEMAR_DEV_ELT_WH;
GRANT USAGE ON WAREHOUSE BLUEMAR_DEV_ELT_WH TO BLUEMAR_DEV_ELT_DEVELOPER_ROLE;
GRANT ALL ON DATABASE BLUEMAR_DEV_DB TO ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE;
GRANT ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE TO USER AOVIEDOM;

USE ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE;

CREATE SCHEMA BLUEMAR_DEV_DB.RAW;
GRANT USAGE ON SCHEMA RAW TO ROLE ACCOUNTADMIN;

USE ROLE ACCOUNTADMIN;

CREATE USER VJNOGUERA
PASSWORD = 'password123456789'
DEFAULT_ROLE = BLUEMAR_DEV_ELT_DEVELOPER_ROLE
DEFAULT_WAREHOUSE = BLUEMAR_DEV_ELT_WH
MUST_CHANGE_PASSWORD = TRUE
COMMENT = 'User for Valery Noguera Jiménez';

CREATE USER NECHAVARRIA
PASSWORD = 'password123456789'
DEFAULT_ROLE = BLUEMAR_DEV_ELT_DEVELOPER_ROLE
DEFAULT_WAREHOUSE = BLUEMAR_DEV_ELT_WH
MUST_CHANGE_PASSWORD = TRUE
COMMENT = 'User for Naomi Echavarria Cascante';

CREATE USER AFONSECA
PASSWORD = 'password123456789'
DEFAULT_ROLE = BLUEMAR_DEV_ELT_DEVELOPER_ROLE
DEFAULT_WAREHOUSE = BLUEMAR_DEV_ELT_WH
MUST_CHANGE_PASSWORD = TRUE
COMMENT = 'User for Adrian Fonseca Coto';

GRANT ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE TO USER VJNOGUERA;
GRANT ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE TO USER NECHAVARRIA;
GRANT ROLE BLUEMAR_DEV_ELT_DEVELOPER_ROLE TO USER AFONSECA;

ALTER USER VJNOGUERA
SET EMAIL = 'vnoguera10969@ufide.ac.cr';

ALTER USER AFONSECA
SET EMAIL = 'afonseca90739@ufide.ac.cr';

ALTER USER AFONSECA
SET PASSWORD = 'Password123456789';

ALTER USER NECHAVARRIA
SET EMAIL = 'nechavarria90562@ufide.ac.cr';

ALTER USER NECHAVARRIA
SET PASSWORD = 'Password123456789';

SHOW USERS;

GRANT USAGE ON SCHEMA 


