version: 2

sources:
  - name: staging
    database: bluemar_dev_db
    schema: raw
    tables:
      - name: raw_ingresos
      - name: raw_gastos_operativos
      - name: raw_inventario de activos
      - name: raw_pago_planillas

