
name: 'BlueMar'
version: '1.0.0'

profile: 'BlueMar'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"



models:
  BlueMar:
    raw:
      +materialized: view
      +schema: raw

    staging:
      +materialized: incremental
      +schema: staging

    analytics:
      +materialized: table
      +schema: analytics
